version: '3'
services:
  app:
    container_name: tkr_karuta_app
    build: .
    ports:
      - 9050:9050
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    stdin_open: true
    tty: true
    command: /bin/sh